language: node_js

matrix:
  include:
    - os: linux
      node_js: 10
      before_install:
        # get version
        - cat /etc/os-release
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - os: osx
      node_js: 10
      before_install:
        # get version
        - system_profiler SPSoftwareDataType
    - os: windows
      node_js: 10
      env:
        - FORCE_COLOR=1
      before_install:
        # get version
        - systeminfo

install:
  - node -v
  - npm -v
  - npm install

script:
  - npm start
