language: node_js

matrix:
  include:
    - os: linux
      node_js: 10
      before_install:
        # get version
        - cat /etc/os-release
    - os: osx
      node_js: 10
      before_install:
        # get version
        - system_profiler SPSoftwareDataType
    - os: windows
      node_js: 10
      before_install:
        # get version
        - systeminfo

install:
  - node -v
  - npm -v
  - npm install

script:
  - npm start
