language: node_js

matrix:
  include:
    - os: linux
      node_js: 10
      before_install:
        # get version
        - cat /etc/os-release
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - os: osx
      node_js: 10
      before_install:
        # get version
        - system_profiler SPSoftwareDataType
        # increase file handles, according to watchman
        # https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits
        # necessary on 10.6 and earlier
        - ulimit -n
        - ulimit -S -n 64000
        - ulimit -n
        - sudo sysctl -w kern.maxfiles=10485760
        - sudo sysctl -w kern.maxfilesperproc=1048576
    - os: windows
      node_js: 10
      env:
        - FORCE_COLOR=1
      before_install:
        # get version
        - systeminfo

install:
  - node -v
  - npm -v
  - npm install

script:
  - npm start
