name: Node CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: info
      run: |
        cat /etc/os-release
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - name: install
      run: npm install
    - name: benchmark
      run: npm start
  macos:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: info
      run: system_profiler SPSoftwareDataType
    - name: install
      run: npm install
    - name: benchmark
      run: npm start
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: info
      run: call systeminfo
      shell: cmd
    - name: install
      run: call npm install
      shell: cmd
    - name: benchmark
      run: call npm start
      shell: cmd
